name: Build
on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}
jobs:
  build_android:
    runs-on: ubuntu-latest
    env:
      CI: "true"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - run: yarn install --check-files --frozen-lockfile
      - run: yarn expo eject
      - run: cd android && ./gradlew
