name: Build
on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}
jobs:
  build_android:
    runs-on: ubuntu-latest
    env:
      CI: "true"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --check-files --frozen-lockfile
      - run: yarn expo build:android
