name: Build
on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}
jobs:
  build_android:
    runs-on: ubuntu-latest
    env:
      CI: "true"
    steps:
      - run: yarn
      - run: yarn expo build:android
